### PR TITLE
update LCOE reporting

### PR DESCRIPTION
**Pull request by fschreyer**
update LCOE plotting script, add LCOE vs. price comparison
update LCOE reporting, add se2fe distribution technologies, add DAC levelized cost, make reporting output flexible for either marginal LCOE, average LCOE or both

### CODE REVIEW

**Review by giannou — COMMENTED** [review]
Is there a way I can test these changes myself? Also, did you run the tests found in the folder "tests"?

**Comment by fschreyer** [comment]
No, I did not run them. 
Run convGDX2CSV_LCOE()

**Comment by giannou** [comment]
Can I use any GDX for my test of your routine?

To test your commits, use the `fulldata.gdx` from your most recent REMIND run (if you don't have a very recent one simply start one -- it's always good to keep up with using the model) and the `old.gdx` attached to the package source code.

Simply run the following command twice with the location of each GDX as argument:

`a <- convGDX2mif("/where/the/first/GDX/is/fulldata.gdx")`
`a <- convGDX2mif("/where/the/second/GDX/is/old.gdx")`

But it's true that this doesn't apply here because you didn't touch the `convGDX2MIF` function.

**Comment by giannou** [comment]
So basically you can merge as soon as the conflicts are resolved..

**Comment by fschreyer** [comment]
Ye, any gdx, I guess. 

Ah ok, why these conflicts. Didnt I build properly? I will check later.

**Pull request merged**
