### PR TITLE
Lcoe reporting

### PR DESCRIPTION
**Pull request by fschreyer**
Rework and extent LCOE reporting and LCOE plot scripts: reporting can calculate new plant (marginal) LCOE components for SE generating technologies (the specific cost at which a capacity would produce over its lifetime if it was added in the respective year). This is stored in a csv file in your output folder. As a plotting script, plotLCOE can be used to check consistency of LCOE with capacity additions in REMIND.

### CODE REVIEW

**Comment by fschreyer** [comment]
The reporting will automatically create a csv file in your output folder with all the LCOE post-processing output. For this I addded the convGDX2CSV_LCOE() function. I will do the corresponding commit in the REMIND scripts soon. This will replace the former LCOE mif-file. I simply chose a csv-file such that it is easier for users to search something in the table as the mif file only allows for limited dimensions. The LCOE plots can be obtained by running output.R scripts. I can briefly present this post-processing and the plotting scripts in the next REMIND meeting.

**Comment by giannou** [comment]
> The reporting will automatically create a csv file in your output folder with all the LCOE post-processing output. For this I addded the convGDX2CSV_LCOE() function. I will do the corresponding commit in the REMIND scripts soon. This will replace the former LCOE mif-file. I simply chose a csv-file such that it is easier for users to search something in the table as the mif file only allows for limited dimensions. The LCOE plots can be obtained by running output.R scripts. I can briefly present this post-processing and the plotting scripts in the next REMIND meeting.

thanks for the clarification! short question: I reviewed the commits and they look ok. Have you done any tests? And, to run a test of my own, how does my `scripts/output/single/LCOEPlot.R` in REMIND have to look like? Or is there no change needed in the script?

**Comment by fschreyer** [comment]
What kind of tests are you thinking of? Testing for different regionmappings? I simply tested it for a REMIND2.1.1 validation run and my REMIND-EU runs. I will update the reporting scripts (reporting.R and plotLCOE.R) in REMIND accordingly once the commit is done.

**Comment by giannou** [comment]
> What kind of tests are you thinking of? 

Testing as described in here: https://github.com/pik-piam/remind/blob/master/README.md

**Comment by fschreyer** [comment]
REMIND output scripts still need to be updated for this to work.

**Pull request merged**
